name: italy_dwh
version: "1.0.0"
config-version: 2

profile: italy_dwh

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - target
  - dbt_packages

models:
  italy_dwh:
    staging:
      +materialized: view
      +schema: staging
    dwh:
      +materialized: table
      +schema: dwh
    marts:
      +materialized: table
      +schema: mart
